name: Trigger auto deployment for pdf-to-markdown

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/pdf-to-markdown-AutoDeployTrigger-b4ab2378-ac78-4a19-8398-0f34b8eba8f7.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.PDFTOMARKDOWN_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.PDFTOMARKDOWN_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.PDFTOMARKDOWN_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: 
          registryUsername: ${{ secrets.PDFTOMARKDOWN_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.PDFTOMARKDOWN_REGISTRY_PASSWORD }}
          containerAppName: pdf-to-markdown
          resourceGroup: sponsership-resource
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


